-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server Version:               PostgreSQL 14.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
-- Server Betriebssystem:        
-- HeidiSQL Version:             12.0.0.6468
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES  */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--CREATE SEQUENCE IF NOT EXISTS SCRIPT_ID_seq AS INTEGER INCREMENT 1 MINVALUE 0 START 0;
-- Exportiere Struktur von Tabelle public.SCRIPT
CREATE TABLE IF NOT EXISTS "USER_SCRIPT" (
	"Name" VARCHAR(50) NOT NULL,
	"ScriptString" TEXT NOT NULL,
	"ID" SERIAL,
	PRIMARY KEY ("Name")
);

ALTER TABLE PUBLIC."USER_SCRIPT" ADD UNIQUE ("ID");

CREATE TABLE IF NOT EXISTS "FTP_CONFIG" (
	"Url" TEXT NOT NULL,
	"User" VARCHAR(50) NULL DEFAULT NULL,
	"Password" VARCHAR(50) NULL DEFAULT NULL,
	"FilePath" TEXT NULL DEFAULT NULL,
	"ScriptId" INTEGER NOT NULL,
	PRIMARY KEY ("Url", "ScriptId"),
	CONSTRAINT "FK_FTP_CONFIG_USER_SCRIPT" FOREIGN KEY ("ScriptId") REFERENCES "USER_SCRIPT" ("ID") ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE "FILE_CONFIG" (
	"SourceFileType" VARCHAR(6) NOT NULL,
	"ScriptId" INTEGER NOT NULL,
	"SetttingsAsJSON" TEXT NULL DEFAULT NULL,
	PRIMARY KEY ("SourceFileType", "ScriptId"),
	CONSTRAINT "FK_FILE_CONFIG_USER_SCRIPT" FOREIGN KEY ("ScriptId") REFERENCES "USER_SCRIPT" ("ID") ON UPDATE NO ACTION ON DELETE NO ACTION
);

-- Exportiere Daten aus Tabelle public.SCRIPT: -1 rows
/*!40000 ALTER TABLE "SCRIPT" DISABLE KEYS */;
INSERT INTO "USER_SCRIPT" ("Name", "ScriptString", "ID") VALUES
	('Test123', 'This is a script entry', 1);

INSERT INTO "FILE_CONFIG" ("SourceFileType", "ScriptId") VALUES ('NONE', '1');

/*!40000 ALTER TABLE "SCRIPT" ENABLE KEYS */;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
