version: "3.7"

services: 
    postgres:
        image: postgres
        restart: always
        environment: 
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgrespw
            - POSTGRES_DB=Zelos_Post_Gre_SQL

        ports: 
            - "5432:5432"